security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_EXPERT_TEACHER: [ROLE_TEACHER]
        ROLE_HEAD_TEACHER: [ROLE_TEACHER]
        ROLE_MODERATOR: [ROLE_USER]
        ROLE_ADMIN: [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: normalizedEmail

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            login_throttling:
                max_attempts: 5
                interval: '15 minutes'
            logout:
                path: app_logout
                target: app_home
                enable_csrf: true

    access_control:
        - { path: ^/health, roles: PUBLIC_ACCESS }
        - { path: ^/kayit, roles: PUBLIC_ACCESS }
        - { path: ^/dogrula/eposta, roles: PUBLIC_ACCESS }
        - { path: ^/giris, roles: PUBLIC_ACCESS }
        - { path: ^/cikis, roles: PUBLIC_ACCESS }
        - { path: ^/hesabim, roles: ROLE_USER }
        - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
        firewalls:
            main:
                login_throttling:
                    max_attempts: 3
                    interval: '1 minute'
